var Weeks = {
	"1":{
		type:"cover",
		covers:[
			"./img/v2/bg/NO1.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"296M",
				url:"http://uiweek.qiniudn.com/UIweek.ibooks"
			},
			pdf:{
				size:"117M",
				url:"http://uiweek.qiniudn.com/UIweek_pdf.zip"
			}
		}
	},
	"2":{
		type:"gift",
		url:"./down_v2.php?k=NO1"
	},
	"3":{
		type:"cover",
		covers:[
			"./img/v2/bg/NO2.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"433M",
				url:"http://uiweek.qiniudn.com/UIweek01_all.ibooks"
			},
			pdf:{
				size:"229M",
				url:"http://uiweek.qiniudn.com/UIweek01_pdf.zip"
			}
		}
	},
	"4":{
		type:"gift",
		url:"./down_v2.php?k=NO2"
	},
	"5":{
		type:"cover",
		covers:[
			"./img/v2/bg/C2.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"48M",
				url:"http://uiweek.qiniudn.com/UIweek02_collection.ibooks"
			},
			pdf:{
				size:"54M",
				url:"http://uiweek.qiniudn.com/UIweek02_collection.zip"
			}
		}
	},
	"6":{
		type:"cover",
		covers:[
			"./img/v2/bg/G2.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"40M",
				url:"http://uiweek.qiniudn.com/UIweek02_group.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek02_group.zip"
			}
		}
	},
	"7":{
		type:"cover",
		covers:[
			"./img/v2/bg/S2.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"34M",
				url:"http://uiweek.qiniudn.com/UIweek02_share.ibooks"
			},
			pdf:{
				size:"19M",
				url:"http://uiweek.qiniudn.com/UIweek02_share.zip"
			}
		}
	},
	"8":{
		type:"cover",
		covers:[
			"./img/v2/bg/N2.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"225M",
				url:"http://uiweek.qiniudn.com/UIweek02_news.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek02_news.zip"
			}
		}
	},
	"9":{
		type:"gift",
		url:"./down_v2.php?k=NO3"
	},
	"10":{
		type:"cover",
		covers:[
			"./img/v2/bg/UX01.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"24M",
				url:"http://uiweek.qiniudn.com/UX茶馆_设计之道.ibooks"
			},
			pdf:{
				size:"6M",
				url:"http://uiweek.qiniudn.com/UX茶馆_设计之道.zip"
			}
		}
	},
	"11":{
		type:"cover",
		covers:[
			"./img/v2/bg/C3.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"58M",
				url:"http://uiweek.qiniudn.com/UIweek03_collection.ibooks"
			},
			pdf:{
				size:"73M",
				url:"http://uiweek.qiniudn.com/UIweek03_collection.zip"
			}
		}
	},
	"12":{
		type:"cover",
		covers:[
			"./img/v2/bg/G3.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"37M",
				url:"http://uiweek.qiniudn.com/UIweek03_group.ibooks"
			},
			pdf:{
				size:"29M",
				url:"http://uiweek.qiniudn.com/UIweek03_group.zip"
			}
		}
	},
	"13":{
		type:"cover",
		covers:[
			"./img/v2/bg/S3.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"31M",
				url:"http://uiweek.qiniudn.com/UIweek03_share.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek03_share.zip"
			}
		}
	},
	"14":{
		type:"cover",
		covers:[
			"./img/v2/bg/N3.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"94M",
				url:"http://uiweek.qiniudn.com/UIweek03_news.ibooks"
			},
			pdf:{
				size:"59M",
				url:"http://uiweek.qiniudn.com/UIweek03_news.zip"
			}
		}
	},
	"15":{
		type:"gift",
		url:"./down_v2.php?k=NO4"
	},
	//,
	/*
	[说明]
	"1":{日期[1-31]
		type:[gift|cover],
		covers:[
			"图片地址1，可使用绝对路径或者相对路径",
			"图片地址2，可使用绝对路径或者相对路径",
			"图片地址3，可使用绝对路径或者相对路径"
		],
		books:{
			ios:{//ios版
				size:"",//显示尺寸
				url:"#"//下载地址
			},
			offline:{//离线版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			},
			pdf:{//pdf版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			}
		}
	},//[!]如果有多个日期请以[,]号结尾，最后一个不要加[,]
	*/
};