var Weeks = {
	year:13,//年
	month:09,//月[01-12]
	"9":{
		type:"cover",
		covers:[
			"./img/v2/bg/c03.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"58M",
				url:"http://uiweek.qiniudn.com/UIweek03_collection.ibooks"
			},
			pdf:{
				size:"73M",
				url:"http://uiweek.qiniudn.com/UIweek03_collection.zip"
			}
		}
	},
	"16":{
		type:"cover",
		covers:[
			"./img/v2/bg/g03.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"37M",
				url:"http://uiweek.qiniudn.com/UIweek03_group.ibooks"
			},
			pdf:{
				size:"29M",
				url:"http://uiweek.qiniudn.com/UIweek03_group.zip"
			}
		}
	},
	"23":{
		type:"cover",
		covers:[
			"./img/v2/bg/s03.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"31M",
				url:"http://uiweek.qiniudn.com/UIweek03_share.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek03_share.zip"
			}
		}
	},
	"28":{
		type:"cover",
		covers:[
			"./img/v2/bg/n03.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"94M",
				url:"http://uiweek.qiniudn.com/UIweek03_news.ibooks"
			},
			pdf:{
				size:"59M",
				url:"http://uiweek.qiniudn.com/UIweek03_news.zip"
			}
		}
	},
	"30":{
		type:"gift",
		url:"./down_v2.php?k=201309"
	},
	/*
	[说明]
	"1":{日期[1-31]
		type:[gift|cover],
		covers:[
			"图片地址1，可使用绝对路径或者相对路径",
			"图片地址2，可使用绝对路径或者相对路径",
			"图片地址3，可使用绝对路径或者相对路径"
		],
		books:{
			ios:{//ios版
				size:"",//显示尺寸
				url:"#"//下载地址
			},
			offline:{//离线版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			},
			pdf:{//pdf版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			}
		}
	},//[!]如果有多个日期请以[,]号结尾，最后一个不要加[,]
	*/
};