var Weeks = {
	year:13,//年
	month:08,//月[01-12]
	"5":{
		type:"cover",
		covers:[
			"./img/v2/bg/c02.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"48M",
				url:"http://uiweek.qiniudn.com/UIweek02_collection.ibooks"
			},
			pdf:{
				size:"54M",
				url:"http://uiweek.qiniudn.com/UIweek02_collection.zip"
			}
		}
	},
	"12":{
		type:"cover",
		covers:[
			"./img/v2/bg/g02.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"40M",
				url:"http://uiweek.qiniudn.com/UIweek02_group.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek02_group.zip"
			}
		}
	},
	"16":{
		type:"cover",
		covers:[
			"./img/v2/bg/UX01.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"24M",
				url:"http://uiweek.qiniudn.com/UX茶馆_设计之道.ibooks"
			},
			pdf:{
				size:"6M",
				url:"http://uiweek.qiniudn.com/UX茶馆_设计之道.zip"
			}
		}
	},
	"19":{
		type:"cover",
		covers:[
			"./img/v2/bg/s02.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"34M",
				url:"http://uiweek.qiniudn.com/UIweek02_share.ibooks"
			},
			pdf:{
				size:"19M",
				url:"http://uiweek.qiniudn.com/UIweek02_share.zip"
			}
		}
	},
	"26":{
		type:"cover",
		covers:[
			"./img/v2/bg/n02.png",
		],
		books:{
			ios:{
				size:"",
				url:"https://itunes.apple.com/cn/app/uiweek/id666201146?mt=8"
			},
			offline:{
				size:"225M",
				url:"http://uiweek.qiniudn.com/UIweek02_news.ibooks"
			},
			pdf:{
				size:"12M",
				url:"http://uiweek.qiniudn.com/UIweek02_news.zip"
			}
		}
	},
	"28":{
		type:"gift",
		url:"./down_v2.php?k=201308"
	},
	/*
	[说明]
	"1":{日期[1-31]
		type:[gift|cover],
		covers:[
			"图片地址1，可使用绝对路径或者相对路径",
			"图片地址2，可使用绝对路径或者相对路径",
			"图片地址3，可使用绝对路径或者相对路径"
		],
		books:{
			ios:{//ios版
				size:"",//显示尺寸
				url:"#"//下载地址
			},
			offline:{//离线版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			},
			pdf:{//pdf版
				size:"42M",//显示尺寸
				url:"#"//下载地址
			}
		}
	},//[!]如果有多个日期请以[,]号结尾，最后一个不要加[,]
	*/
};